name: "BuildingManager"
services:
    postgres:
        image: postgres:17.3
        container_name: BuildingManagerPostgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            POSTGRES_DB: BuildingManager
        ports:
            - "5432:5432"
    redis:
        image: redis:latest
        container_name: BuildingManagerRedis
        restart: always
        ports:
            - "6379:6379"
    backend:
        image: nguyentienminh0710/buildingmanager:0.0.6
        container_name: BuildingManagerBackend
        restart: always
        env_file: ".env"
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_PORT: 6379
            REDIS_HOST: redis
        ports:
            - "8080:8080"
        depends_on:
            - postgres
            - redis